apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: geth-miner-deployment
  labels:
    app: geth-miner
spec:
  replicas: 3
  selector:
    matchLabels:
      app: geth-miner
  template:
    metadata:
      labels:
        app: geth-miner
    spec:
      containers:
      - name: geth-miner
        image: ethereum/client-go:v1.7.2
        command: ["/bin/sh"]
        args: 
        - "-c"
        - "geth --bootnodes=`cat /root/.ethereum/bootnodes` --mine --etherbase=0 --networkid=${NETWORK_ID} --ethstats=${HOSTNAME}:${ETHSTATS_SECRET}@ethstats-service.default --verbosity=5"
        env:
        - name: ETHSTATS_SECRET
          valueFrom:
            secretKeyRef:
              name: ethstats-secret
              key: WS_SECRET
        - name: NETWORK_ID
          valueFrom:
            configMapKeyRef:
              name: geth-config
              key: networkid
        ports:
        - name: discovery-udp
          containerPort: 30303
          protocol: UDP
        - name: discovery-tcp
          containerPort: 30303
        volumeMounts:
        - name: data
          mountPath: /root/.ethereum
      initContainers:
      - name: init-genesis
        image: ethereum/client-go:v1.7.2
        args:
        - "init"
        - "/var/geth/genesis.json"
        volumeMounts:
        - name: data
          mountPath: /root/.ethereum
        - name: config
          mountPath: /var/geth
      - name: create-account
        image: ethereum/client-go:v1.7.2
        command: ["/bin/sh"]
        args:
        - "-c"
        - "printf '$(ACCOUNT_SECRET)\n$(ACCOUNT_SECRET)\n' | geth account new"
        env:
        - name: ACCOUNT_SECRET
          valueFrom:
            secretKeyRef:
              name: geth-miner-secret
              key: accountsecret
        volumeMounts:
        - name: data
          mountPath: /root/.ethereum
      - name: get-bootnodes
        image: ethereum/client-go:v1.7.2
        command: ["/bin/sh"]
        args:
        - "-c"
        - |-
          apk add --no-cache curl; 
          CNT=0;
          while [ $CNT -le 30 ] 
          do
            curl -s bootnode-registrar-service.default | xargs echo -n >> /geth/bootnodes;
            if [ -s /geth/bootnodes ] 
            then
              exit 0;
            fi;

            echo "no bootnodes found. retrying $CNT..."; 
            sleep 1 || break;
            CNT=$((CNT+1));
          done;
          exit 1;
        volumeMounts:
        - name: data
          mountPath: /geth
      volumes:
      - name: data
        emptyDir: {}
      - name: config 
        configMap:
          name: geth-config