apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: {{ template "ethereum.fullname" . }}-ethstats-deployment
  labels:
    app: {{ template "ethereum.name" . }}-ethstats-deployment
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.ethstats.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ethereum.name" . }}-ethstats
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ethereum.name" . }}-ethstats
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: ethstats
        image: {{ .Values.ethstats.image.repository }}:{{ .Values.ethstats.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: WS_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "ethereum.fullname" . }}-ethstats-secret
              key: WS_SECRET